version: '3.8'

services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: todo-list-db
    environment:
      - 'POSTGRES_DB=notedatabase'
      - 'POSTGRES_PASSWORD=159753'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d notedatabase" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-list-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/notedatabase
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 159753
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped