spring.application.name=practice-project
spring.datasource.url=jdbc:postgresql://localhost:5432/notedatabase
spring.datasource.username=postgres
spring.datasource.password=159753
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-init-sql=CREATE SCHEMA IF NOT EXISTS public;
spring.thymeleaf.check-template-location=false
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.default-schema=public
spring.liquibase.liquibase-schema=public
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false